version: "3.2"
services:
  php:
    build: './php/'
    container_name: lamp_php
    networks:
      - backend
    ports:
      - 9000:9000
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mariadb:latest
    container_name: lamp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=roberto
    networks:
      - backend
    volumes:
      - $HOME/Docker/mariadb/data:/var/lib/mysql
  apache:
    build: './apache/'
    container_name: lamp_apache
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
networks:
  frontend:
  backend: